defaults:
  theory:
    camb:
      extra_args:
            kmax: 10
            k_per_logint: 130
            nonlinear: true
            lens_potential_accuracy: 8
            lens_margin: 2050
            lAccuracyBoost: 1.2
            min_l_logl_sampling: 6000
            DoLateRadTruncation: false
  timing: True
  # Presets for shorter input
  # Any other field overwrites the presets
  preset:
    # Base model
    primordial: SFSR
    geometry: flat
    hubble: sound_horizon_last_scattering
    matter: omegab_h2, omegac_h2
    neutrinos: one_heavy_planck
    dark_energy: lambda
    bbn: consistency
    reionization: std
    # Sampler
    sampler: MCMC
    # Theory code
    theory: camb
  params:
    thetastar:
      latex: \theta_\star
      derived: true
    sigma8:
      latex: \sigma_8
      derived: true
    zrei:
      latex: z_\mathrm{reio}
      derived: true
    rstar:
      latex: r_{s,\star}
      derived: true
    rdrag:
      latex: r_\mathrm{drag}
    omegam:
      latex: \Omega_{\mathrm{m}}
importance_defaults: # defaults for importance runs
minimize_defaults: # defaults for minimization runs
getdist_options: # any non-default options to pass to getdist
groups: # the list of groups sub-grids to run
  main:
    models:
      - ""
    # NB: datasets infos are added *after* models info,
    # so the former overwrite the latter in case of conflict.
    datasets:
      - planck_lowl_NPIPE_TTTEEE_aplensing
      - planck_lowl_NPIPE_TTTEEE_aplensing_DESI
      - planck_lowl_NPIPE_TTTEEE_DESI
      - planck_lowl_NPIPE_actpol
      - planck_lowl_lite_actpol
      - planck_lowl_lite_actpol_aplensing_DESI
      - planck_lowl_NPIPE_TTTEEE_aplensing_DESI_actlite
      
# post-processing (e.g. importance reweighting)
#   importance_runs:
#        - [...]
    # Group-level skip combinations
    skip:
      # model: [dataset1, ...]
# Global skip combinations
skip:
  # model: [name1, ...]
# Definitions of the models used
models:
  "":
# Definitions of datasets used
datasets:
  planck_lowl_NPIPE_TTTEEE_aplensing:
    likelihood:
      planck_2018_lowl.TT:
      planck_2018_lowl.EE_sroll2:
      planck_NPIPE_highl_CamSpec.TTTEEE:
      act_dr6_lenslike.ACTDR6LensLike:
        package_install: pip
        lens_only: false
        stop_at_error: true
        lmax: 4000
        variant: actplanck_baseline
  planck_lowl_NPIPE_TTTEEE_aplensing_DESI:
    likelihood:
      bao.desi_dr2:
      planck_2018_lowl.TT:
      planck_2018_lowl.EE_sroll2:
      planck_NPIPE_highl_CamSpec.TTTEEE:
      act_dr6_lenslike.ACTDR6LensLike:
        package_install: pip
        lens_only: false
        stop_at_error: true
        lmax: 4000
        variant: actplanck_baseline
  planck_lowl_NPIPE_TTTEEE_DESI:
    likelihood:
      bao.desi_dr2:
      planck_2018_lowl.TT:
      planck_2018_lowl.EE_sroll2:
      planck_NPIPE_highl_CamSpec.TTTEEE:
  planck_lowl_NPIPE_actpol:
    likelihood:
      planck_2018_lowl.TT:
      planck_2018_lowl.EE_sroll2:
      planck_NPIPE_highl_CamSpec.TTTEEE:
      act_dr6_cmbonly:
        ell_cuts:
              TT:
              - 2200
              - 8500
              TE:
              - 600
              - 8500
              EE:
              - 600
              - 8500
        params:
              A_act:
                value: 'lambda A_planck: A_planck'
                latex: A_{\rm ACT}
                derived: true
              P_act:
                prior:
                  min: 0.9
                  max: 1.1
                ref:
                  dist: norm
                  loc: 1.0
                  scale: 0.01
                proposal: 0.01
                latex: p_{\rm ACT} 
  planck_lowl_lite_actpol:
   likelihood:
     planck_2018_lowl.TT:
     planck_2018_lowl.EE_sroll2:
     act_dr6_cmbonly.PlanckActCut:
        dataset_params:
          use_cl: tt te ee
          lmin_cuts: 0 0 0
          lmax_cuts: 2200 600 600
        aliases:
        - plikHM_TTTEEE
     act_dr6_cmbonly:
        ell_cuts:
              TT:
              - 2200
              - 8500
              TE:
              - 600
              - 8500
              EE:
              - 600
              - 8500
        params:
              A_act:
                value: 'lambda A_planck: A_planck'
                latex: A_{\rm ACT}
                derived: true
              P_act:
                prior:
                  min: 0.9
                  max: 1.1
                ref:
                  dist: norm
                  loc: 1.0
                  scale: 0.01
                proposal: 0.01  
  planck_lowl_lite_actpol_aplensing_DESI:
   likelihood:
     bao.desi_dr2:
     act_dr6_lenslike.ACTDR6LensLike:
        package_install: pip
        lens_only: false
        stop_at_error: true
        lmax: 4000
        variant: actplanck_baseline
     planck_2018_lowl.TT:
     planck_2018_lowl.EE_sroll2:
     act_dr6_cmbonly.PlanckActCut:
        dataset_params:
          use_cl: tt te ee
          lmin_cuts: 0 0 0
          lmax_cuts: 2200 600 600
        aliases:
        - plikHM_TTTEEE
     act_dr6_cmbonly:
        ell_cuts:
              TT:
              - 2200
              - 8500
              TE:
              - 600
              - 8500
              EE:
              - 600
              - 8500
        params:
              A_act:
                value: 'lambda A_planck: A_planck'
                latex: A_{\rm ACT}
                derived: true
              P_act:
                prior:
                  min: 0.9
                  max: 1.1
                ref:
                  dist: norm
                  loc: 1.0
                  scale: 0.01
                proposal: 0.01  
  planck_lowl_NPIPE_TTTEEE_aplensing_DESI_actlite:
    likelihood:
      act_dr6_cmbonly:
        ell_cuts:
              TT:
              - 2200
              - 8500
              TE:
              - 1000
              - 8500
              EE:
              - 1000
              - 8500
        params:
              A_act:
                value: 'lambda A_planck: A_planck'
                latex: A_{\rm ACT}
                derived: true
              P_act:
                prior:
                  min: 0.9
                  max: 1.1
                ref:
                  dist: norm
                  loc: 1.0
                  scale: 0.01
                proposal: 0.01  
      bao.desi_dr2:
      planck_2018_lowl.TT:
      planck_2018_lowl.EE_sroll2:
      planck_NPIPE_highl_CamSpec.TTTEEE:
      act_dr6_lenslike.ACTDR6LensLike:
        package_install: pip
        lens_only: false
        stop_at_error: true
        lmax: 4000
        variant: actplanck_baseline     
cov_dir: null # where to look for covariance matrices  (for efficient exploration)
cov_map:
 # try to match each new run name to existing covmat
  without: ['lensing', 'BAO']
  rename:
      NPIPE: plikHM
      lowl: ['lowl', 'lowE']


